export const TEST_ACTION = 'TEST_ACTION';
export const FETCH_DATA = 'FETCH_DATA';
export const REQUESTED_DATA = 'REQUESTED_DATA';
export const REQUESTED_SUCCESS = 'REQUESTED_SUCCESS';
export const REQUESTED_FAILED = 'REQUESTED_FAILED';